# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-01 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=15, verbose_name='医生姓名')),
                ('account', models.CharField(max_length=15, unique=True, verbose_name='登录账号')),
                ('upwd', models.CharField(max_length=12, verbose_name='密码')),
                ('workday', models.CharField(choices=[('1', '星期一'), ('2', '星期二'), ('3', '星期三'), ('4', '星期四'), ('5', '星期五'), ('6', '星期六'), ('7', '星期天')], default='1', max_length=15, verbose_name='值班时间')),
                ('client', models.CharField(choices=[('1', '科室一'), ('2', '科室二'), ('3', '科室三'), ('4', '科室四'), ('5', '科室五'), ('6', '科室六')], default='1', max_length=15, verbose_name='科室')),
            ],
            options={
                'verbose_name_plural': '医生',
                'db_table': 'Doctors',
                'verbose_name': '医生',
            },
        ),
    ]
