# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-02 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pat_id', models.CharField(max_length=18)),
                ('pat_phone', models.CharField(max_length=11)),
                ('client', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'Line',
            },
        ),
        migrations.AlterField(
            model_name='doctors',
            name='client',
            field=models.CharField(choices=[('1', '内科'), ('2', '五官科'), ('3', '神经科'), ('4', '骨科'), ('5', '分泌科'), ('6', '外科')], default='1', max_length=15, verbose_name='科室'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='upwd',
            field=models.CharField(max_length=12, verbose_name='登录密码'),
        ),
    ]
